// THIS FILE IS AUTO-GENERATED BY buildinfo.py
#define GIT_REPO "C:/Users/d91454/workspace/quantlib-old/QuantLib"
#define GIT_BRANCH "localCorrSSch"
#define GIT_COMMIT_ID "b73bce14109cfb46ca912db82e821529bc03fd17"
#define GIT_COMMIT_ID_SHORT "b73bce141"
#define GIT_WORKING_DIR_STATUS " M QuantLib_vc11.vcxproj.filters\n M buildinfo.hpp\n M ql/experimental/volatility/Makefile.am\n M ql/experimental/volatility/all.hpp\n"
#define GIT_BUILD_INFO_NOW "2019-03-08 16:59:15.357674"
